app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('peliculas/', views.peliculas, name='peliculas'),
    path('peliculas/<int:id>/', views.pelicula, name='pelicula'),
    path('categorias/', views.categorias, name='categorias'),

]

blockbuster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Lista de Peliculas
lista = [
    {'id': 0, 'nombre': 'Pulp Fiction', 'year': 1998},
    {'id': 1, 'nombre': 'Your Name', 'year': 2015},
    {'id': 2, 'nombre': 'Django Unchained', 'year': 2013},
    {'id': 3, 'nombre': 'A Silent Voice', 'year': 2014},
]


def index(request):
    return render(request, 'app/index.html')


def peliculas(request):
    contexto = {
        'lista_peliculas': lista,
        'year': 2020,
        'tienda': 'Blockbuster',

    }
    return render(request, 'app/peliculas.html', contexto)


def pelicula(request, id):
    contexto = {}

    # Verifica que el ID este dentro de la lista
    if id < len(lista):
        # Crea una nueva propiedad en el contexto
        contexto['pelicula'] = lista[id]

# Muestra el Template con la información del contexto
    return render(request, 'app/pelicula.html', contexto)


def categorias(request):
    return render(request, 'app/categorias.html')

app/templates/app/categorias.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorias</title>
</head>

<body>
    <h1>Categorias</h1>
    <ul>
        <li>Acción</li>
        <li>Comedia</li>
        <li>Documental</li>
    </ul>
</body>

</html>

app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blockbuster</title>
</head>

<body>
    <h1>BLOCKBUSTER</h1>
    <h3>Bienvenido a su tienda de Confianza</h3>
    <a href="{% url 'app:peliculas' %}">Peliculas</a>
    <br>
    <a href="{% url 'app:categorias' %}">Categorias</a>
    <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Numquam,
        consequuntur molestiae qui doloremque explicabo quibusdam maiores earum
        consectetur, odit, molestias recusandae impedit error ipsam porro
        provident aut animi. Porro, culpa.
    </p>
    <hr>
    <h2>Todos los Derechos Reservados</h2>
</body>

</html>

app/templates/app/pelicula.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pelicula</title>
</head>

<body>
    {% if pelicula %}
    <!--  #if que solo habilita la pagina cuando detecte un titulo que venga desde el view -->
    <h1>{{ pelicula.nombre }}</h1>
    <h3>{{pelicula.year}}</h3>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci
        accusamus quos quod molestias nesciunt excepturi est blanditiis cumque, a
        qui nulla unde velit explicabo praesentium cum! Numquam eos culpa cumque?
    </p>
    {%else%}
    <h1 style="color: red">La película solicitada no existe</h1>
    {%endif%}
</body>

</html>

app/templates/app/peliculas.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Peliculas</title>
</head>

<body>
    <h1>Peliculas</h1>
    <a href="{%  url 'app:pelicula' 0 %}">Pulp Fiction</a>

    <table border="1" width="100%">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Año</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for p in lista_peliculas %}
            <tr>
                <td>{{ p.nombre}}</td>
                <td>{{ p.year}}</td>
                <td>
                    <a href="{%  url 'app:pelicula' p.id %}">Ver</a> </td>
            </tr>
            {%endfor%}
        </tbody>
    </table>




    <hr>
    <span>Todos los Derechos Reservados {{year}} - {{tienda}}</span>
</body>

</html>